image: gcc

stages:
  - test

before_script:
  - apt update && apt -y install autoconf automake libtool libgudev-1.0-dev autoconf-archive

test-no-mbim-no-qrtr:
  stage: test
  script:
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --disable-mbim-qmux --disable-qrtr
    - make
    - make check
    - make install

test-no-mbim:
  stage: test
  script:
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --disable-mbim-qmux --enable-qrtr
    - make
    - make check
    - make install

test-no-qrtr:
  stage: test
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - make install
    - popd
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --enable-mbim-qmux --disable-qrtr
    - make
    - make check
    - make install

test-default:
  stage: test
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - make install
    - popd
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --enable-mbim-qmux --enable-qrtr
    - make
    - make check
    - make install
