image: gcc

stages:
  - test

before_script:
  - apt update && apt -y install autoconf automake libtool libgudev-1.0-dev autoconf-archive
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

test:
  stage: test
  script:
    - ./autogen.sh
    - make
    - make check
    - make install

test-mbim-qmux:
  stage: test
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - ./autogen.sh
    - make
    - make install
    - popd
    - ./autogen.sh --enable-mbim-qmux
    - make
    - make check
    - make install
